config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :messages
  get 'site/index'

  devise_for :users
  resources :bookmarks

  root :to => 'messages#index'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
	belongs_to :user

	#vérifier d'un utilisateur est connecté
	validates :user_id, presence: true

	#Vérifier que le titre est présent et qu'il fait au moins 5 caractères
	validates :title, length: {minimum: 5}, presence: true

	#vérifier que l'url est présente et respect le format
	validates :url, format: {with: Regexp.new(URI::regexp(%w(http https)))}, presence: true

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user

  #vérifier d'un utilisateur est connecté
  validates :user_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,:trackable, :validatable
  has_many :messages
  has_many :bookmarks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!
  action :set_bookmark, only: [:show, :edit, :update, :destroy]

  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmarks = current_user.bookmarks.all
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
    @bookmark = current_user.bookmarks.find(params[:id])
  end

  # GET /bookmarks/new
  def new
    @bookmark = current_user.bookmarks.new
  end

  # GET /bookmarks/1/edit
  def edit
    @bookmark = current_user.bookmarks.find(params[:id])
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = current_user.bookmarks.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    @bookmark = current_user.bookmarks.find(params[:id])
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark = current_user.bookmarks.find(params[:id])
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      unless @bookmark = current_user.bookmarks.find(params[:id]).first
        flash[:alert] = 'Bookmark not found.'
        redirect_to root_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:title, :url)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  action :set_message, only: [:show, :edit, :update, :destroy]

  def index
    @messages = current_user.messages.order("created_at DESC")
  end

  def show
    @message = current_user.messages.find(params[:id])
  end

  def new
    @message = current_user.messages.new
  end

  def create
    @message = current_user.messages.new(message_params)
    if @message.save
      redirect_to messages_path, notice: "The message has been successfully created."
    else
      render action: "new"
    end
  end

  def edit
    @message = current_user.messages.find(params[:id])
    @messages = current_user.messages.order("created_at DESC")
  end

  def update
    @message = current_user.messages.find(params[:id])
    if @message.update_attributes(message_params)
      redirect_to messages_path, notice: "The message has been successfully updated."
    else
      render action: "edit"
    end
  end

  private

  def message_params
    params.require(:message).permit(:title, :body)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    # retrieve all Bookmarks ordered by descending creation timestamp
    @bookmarks = Bookmark.order('created_at desc')
    @messages = Message.order('created_at desc')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for(@bookmark) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :url %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing Bookmark</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bookmarks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.title %></td>
        <td><%= bookmark.url %></td>
        <td><%= link_to 'Show', bookmark %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
        <td><%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookmark', new_bookmark_path %>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render 'form' %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <td><%= @bookmark.title %></td>

</p>

<p>
  <strong>Url:</strong>
  <td><%= @bookmark.url %></td>
</p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/messages/_form.slim
- if @message.errors.any?
  ul
    = @message.errors.full_messages.each do |message|
      li
        = message
= simple_form_for @message do |f|
  .form-inputs
    | Code
    = f.text_field :title
    | Contenu
    = f.cktext_area :body, rows: 10
  .form-actions
    = f.button :submit

app/views/messages/edit.slim
doctype html
html.no-js[lang="en"]
  head
    meta[charset="utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      | KMarketing
    link[rel="stylesheet" href="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css"]
  body
    .off-canvas-wrapper
      .off-canvas-wrapper-inner data-off-canvas-wrapper=""
        #my-info.off-canvas.position-left.reveal-for-large data-off-canvas="" data-position="left"
          .row.column
            - @messages.each do |message|
              .column
                ul.accordion data-accordion="" data-allow-all-closed="true"
                  li.accordion-item data-accordion-item=""
                    a.accordion-title
                      | Code :
                      = message.title.html_safe
                    .accordion-content data-tab-content=""
                      .callout.secondary
                        = link_to message.body.html_safe, edit_message_path(message)
        .off-canvas-content data-off-canvas-content=""
          .title-bar.hide-for-large
            .title-bar-left
              button.menu-icon data-open="my-info" type="button"
              span.title-bar-title
                | Messages
          .row
            = render "form"

app/views/messages/index.slim
doctype html
html.no-js[lang="en"]
  head
    meta[charset="utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      | KMarketing
    link[rel="stylesheet" href="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css"]
  body
    .top-bar
      .top-bar-left
        ul.menu
          li.menu-text
            | KMarketing

      .top-bar-right
        ul.menu

          == yield

          - unless user_signed_in?
            li
              = link_to('Sign up', user_registration_path, :method => :post)
            li
              = link_to('Sign in', user_session_path, :method => :post)
          - else
            li
              = link_to(current_user.email, edit_user_registration_path)
            li
              = link_to('Logout', destroy_user_session_path, :method => :delete)


    .callout.large
      .row.column.text-center
        == yield

        - unless user_signed_in?
          | Connecter vous au service pour commencer a utiliser KMarketing
        - else
          a.button.large href=new_message_path
            | Créer votre message

    .row.column
      h3
        | Recent Work
    .row.medium-up-3.large-up-4
      == yield

      - if user_signed_in?
        - @messages.each do |message|
          .column
            ul.accordion data-accordion="" data-allow-all-closed="true"
              li.accordion-item data-accordion-item=""
                a.accordion-title
                  | Code :
                  = message.title.html_safe
                .accordion-content data-tab-content=""
                  .callout.secondary
                    = link_to message.body.html_safe, edit_message_path(message)

    script[src="https://code.jquery.com/jquery-2.1.4.min.js"]
    script[src="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"]
    script
      |  $(document).foundation();

app/views/messages/new.slim
h3
  |  New Article
= render "form"

app/views/site/index.html.erb
<% if current_user %>
    <h2>Latest Bookmarks</h2>
    <table style="width: 100%">
      <thead>
      <tr>
        <th>Url</th>
      </tr>
      </thead>

      <tbody>
      <% @bookmarks.each do |bookmark| %>
          <tr>
            <td><%= link_to bookmark.title, bookmark.url %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

<% else %>
    <div class="panel">
      <h1>Share your bookmarks!</h1>
      <p>A simple app to track and share your beloved bookmarks with others.</p>
      <%= link_to "Get started today", new_user_registration_path, :class => "button button-large" %>
    </div>

    <hr>

    <div class="row">
      <div class="large-8 columns">
        <h3>12 Devs of Summer</h3>
        <p>
          12 Devs is an evolution of the 12 Devs of Xmas, a way to bring more cool web development articles to you throughout the year. However 12 Devs won’t just be about the tutorial and tips articles, we’re also going to be bringing you some great new features and events.
        </p>
        <p><a class="" href="http://12devs.co.uk" target="_blank">Learn more</a>.</p>
      </div>
      <div class="large-4 columns">
        <h3>About this app</h3>
        <p>This is a tutorial app developed by <a href="http://andreapavoni.com" target="_blank">Andrea Pavoni</a> as a companion to the rails article. Check the source code on <a href="http://github.com/apeacox/12dos-bookmarks" target="_blank">GitHub</a>. </p>
      </div>
    </div>
<% end %>

app/views/site/index.slim
doctype html
html.no-js[lang="en"]
  head
    meta[charset="utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      | Foundation | Welcome
    link[rel="stylesheet" href="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css"]
  body
    .top-bar
      .top-bar-left
        ul.menu
          li.menu-text
            | Bookmark Manager

      .top-bar-right
        ul.menu

          == yield

          - unless user_signed_in?
            li
              = link_to('Sign up', user_registration_path, :method => :post)
            li
              = link_to('Sign in', user_session_path, :method => :post)
          - else
            li
              = link_to(current_user.email, edit_user_registration_path)
            li
              = link_to('Logout', destroy_user_session_path, :method => :delete)


    .callout.large
      .row.column.text-center
        h1
          | Changing the World Through Design
        p.lead
          | Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dui mauris.
        a.button.large[href="#"]
          | Learn More
        a.button.large.hollow[href="#"]
          | Learn Less
    .row.column
      h3
        | Our Recent Work
    .row.medium-up-3.large-up-4
      -@bookmarks.each do |bookmark|
        .column
          = link_to bookmark.title, bookmark.url

    hr
    .row.column
      ul.menu
        li
          a[href="#"]
            | One
        li
          a[href="#"]
            | Two
        li
          a[href="#"]
            | Three
        li
          a[href="#"]
            | Four
    script[src="https://code.jquery.com/jquery-2.1.4.min.js"]
    script[src="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"]
    script
      |  $(document).foundation();